language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t jagveer/docker-react -f Dockerfile.dev

script:
  - docker run -e CI=true jagveer/docker-react npm run test -- --coverage
